Backend1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "NGO Admin"
admin.site.site_title = "NGO"
admin.site.index_title = "NGO Administration Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from .views import (
    EventDetailView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    AchievementDetailView,
    AchievementCreateView,
    AchievementUpdateView,
    AchievementDeleteView,
)

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
    
    path('accounts/signup/', views.signup_view, name="signup"),
    path('accounts/login/', views.login_view, name="login"),
    path('accounts/logout/', views.logout_view, name="logout"),

    path('event/<slug>/', EventDetailView.as_view(), name='event-detail'),
    path('new/', EventCreateView.as_view(), name='event-add'),
    path('events_list/', views.events_list, name='events_list'),
    path('event-update/<slug>/', EventUpdateView.as_view(), name='event-update'),
    path('event-delete/<slug>/', EventDeleteView.as_view(), name='event-delete'),

    path('completed_list/', views.completed_list, name='completed_list'),
    path('completed/<int:pk>/', AchievementDetailView.as_view(), name='achievement-detail'),
    path('achievement_new/', AchievementCreateView.as_view(), name='achievement-add'),
    path('achievement-update/<int:pk>/', AchievementUpdateView.as_view(), name='achievement-update'),
    path('achievement-delete/<int:pk>/', AchievementDeleteView.as_view(), name='achievement-delete'),

    path('donation_form/', views.donation_form, name='donation_form'),
    path('donate', views.donateFunds, name="donateFunds"),
    path('donations_received/', views.donations_received, name="donations_received"),

    path('volunteering/<slug>/', views.become_volunteer, name="volunteering"),
    path('user_dashboard/', views.user_dashboard, name="user_dashboard"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.shortcuts import reverse
from django.utils import timezone

class User(AbstractUser):
    mobile_number = models.CharField(max_length=10, unique=True)
    address = models.CharField(max_length=150)

class Event(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="event_creator", on_delete=models.CASCADE)
    volunteers = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name="volunteers",blank=True)
    title = models.CharField(max_length=75)
    description = models.TextField()
    cause = models.CharField(max_length=100)
    location = models.CharField(max_length=150)
    volunteers_required = models.IntegerField(default=1)
    duration = models.CharField(max_length=20)
    event_timings = models.DateTimeField(default=timezone.now)
    is_complete = models.BooleanField(default=False)
    slug = models.SlugField(default="event_name")

    def __str__(self):
        return self.title
      
    def get_absolute_url(self):
        return reverse("main:event-detail", kwargs={
            'slug': self.slug
        })

    def get_event_delete_url(self):
        return reverse("main:event-delete", kwargs={
            'slug': self.slug
        })

    def get_update_event_url(self):
        return reverse("main:event-update", kwargs={
            'slug': self.slug
        })

class Achievement(models.Model):
    event = models.OneToOneField(Event,on_delete=models.CASCADE)
    details = models.TextField()
    impact_on_society = models.TextField()
    awards = models.TextField(blank=True)
    funds_used = models.FloatField()
    image1 = models.ImageField(default='default.png', upload_to='images/')
    image2 = models.ImageField(default='default.png', upload_to='images/')
    image3 = models.ImageField(default='default.png', upload_to='images/')

    def __str__(self):
        return self.event.title

    def get_absolute_url(self):
        return reverse("main:achievement-detail", kwargs={
            'pk': self.pk
        })

    def get_event_delete_url(self):
        return reverse("main:achievement-delete", kwargs={
            'pk': self.pk
        })

    def get_update_event_url(self):
        return reverse("main:achievement-update", kwargs={
            'pk': self.pk
        })

class Donation(models.Model):
    PAYMENT_METHOD = (
        ('BankTransfer', 'BankTransfer'),
        ('PayTM', 'PayTM'),
        ('GooglePay', 'GooglePay'),
        ('CreditCard', 'CreditCard'),
        ('DebitCard', 'DebitCard')
    )
    donated_by = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="donor", on_delete=models.CASCADE, editable = False)
    amount_donated = models.FloatField(editable = False)
    donated_on = models.DateField(default=timezone.now, editable = False)
    pancard = models.CharField(max_length=10, editable = False)
    bank_name = models.CharField(max_length=25, editable = False)
    bank_branch = models.CharField(max_length=50, editable = False)
    payment_method = models.CharField(max_length=12, choices=PAYMENT_METHOD, editable=False)

    def __str__(self):
        return self.donated_by.username

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    mobile_number = forms.CharField(required=True)
    address = forms.CharField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "mobile_number", "address", "first_name", "last_name", "password1", "password2")

    def save(self,commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.mobile_number = self.cleaned_data["mobile_number"]
        user.address = self.cleaned_data["address"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from .models import Event,Achievement,Donation,User
from django.contrib import messages
from django.views.generic import (
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Sum
from .decorators import *

"""
HomePage
"""

def home(request):
    upcoming_events = Event.objects.filter(is_complete=False)
    achievements = Achievement.objects.filter(event__is_complete=True)
    context = {
        'upcoming_events' : upcoming_events,
        'achievements' : achievements,
    }
    return render(request, 'main/home.html',context)

"""
Authentication
"""

def signup_view(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:home')
    else:
        form = NewUserForm()
    return render(request, 'main/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('main:home')
    else:
        form = AuthenticationForm()
    return render(request, 'main/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('/')

"""
Events_CRUD
"""

class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    fields = ['title', 'description', 'cause', 'location', 'volunteers_required', 'duration', 'event_timings', 'slug']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

@login_required
@admin_required
def events_list(request):
    events = Event.objects.filter(created_by=request.user)
    for event in events:
        volunteerscount = event.volunteers.all().count()
    context = {
        'events':events,
        'volunteerscount':volunteerscount,
    }
    return render(request, "main/event_list.html", context)  

class EventDetailView(DetailView):
    model = Event
    template_name = 'main/event_detail.html'

class EventUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Event
    fields = ['title', 'description', 'cause', 'location', 'volunteers_required', 'duration', 'event_timings', 'is_complete', 'slug']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        event = self.get_object()
        if self.request.user == event.created_by:
            return True
        return False

class EventDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Event
    success_url = '/events_list'

    def test_func(self):
        event = self.get_object()
        if self.request.user == event.created_by:
            return True
        return False

"""
Achievements CRUD
"""

class AchievementCreateView(LoginRequiredMixin, CreateView):
    model = Achievement
    fields = ['event', 'details', 'impact_on_society', 'awards', 'funds_used', 'image1', 'image2', 'image3']

    def form_valid(self, form):
        form.instance.event__created_by = self.request.user
        form.instance.event__is_complete = True
        return super().form_valid(form)

@login_required
@admin_required
def completed_list(request):
    completed_events = Achievement.objects.filter(event__is_complete=True)
    context = {
        'completed_events' : completed_events
    }
    return render(request, "main/completed_list.html", context)

class AchievementDetailView(DetailView):
    model = Achievement
    template_name = 'main/achievement_detail.html'

class AchievementUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Achievement
    fields = ['details', 'impact_on_society', 'awards', 'funds_used','image1', 'image2', 'image3']

    def form_valid(self, form):
        form.instance.events__created_by = self.request.user
        form.instance.event__is_complete = True
        return super().form_valid(form)

    def test_func(self):
        achievement = self.get_object()
        if self.request.user == achievement.event.created_by and achievement.event.is_complete == True:
            return True
        return False

class AchievementDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Achievement
    success_url = '/completed_list'

    def test_func(self):
        achievement = self.get_object()
        if self.request.user == achievement.event.created_by and achievement.event.is_complete == True:
            return True
        return False

"""
Donations
"""

def donation_form(request):
    return render(request, 'main/donation_form.html')

@login_required
def donateFunds(request):
    if request.method == "POST":
        donated_by = request.user
        amount_donated = request.POST.get("amount_donated")
        donated_on = timezone.now()
        pancard = request.POST.get("pancard")
        bank_name = request.POST.get("bank_name")
        bank_branch = request.POST.get("bank_branch")
        payment_method = request.POST.get("payment_method")

        donations = Donation(donated_by=donated_by,amount_donated=amount_donated,donated_on=donated_on,pancard=pancard,bank_name=bank_name,bank_branch=bank_branch,payment_method=payment_method)
        donations.save()
    messages.info(request, "Thankyou For Your Contributions!!!")
    return redirect('/')

@login_required
@admin_required
def donations_received(request):
    donations = Donation.objects.all()
    context = {
        'donations' : donations
    }
    return render(request, 'main/donations.html', context)

@login_required
def become_volunteer(request,slug):
    user = request.user
    events=Event.objects.filter(slug=slug)
    for event in events:
        event.volunteers.add(user)
    messages.success(request, "Thankyou for volunteering with us!!We shall shortly update you with the details!!!")
    return redirect('/')

@login_required
def user_dashboard(request):
    donations = Donation.objects.filter(donated_by=request.user)
    volunteers = Event.objects.filter(volunteers=request.user)
    context = {
        'donations' : donations,
        'volunteers' : volunteers,
    }
    return render(request, 'main/user_dashboard.html', context)

main/templates/main/achievement_confirm_delete.html
{% extends "main/layout.html" %}
{% block content %}
    <div class="content-section container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Achievement</legend>
                <h2>Are you sure you want to delete this Achievement!!</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'main:home' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

main/templates/main/achievement_detail.html
{% extends "main/layout.html" %}
{% block content %}
<div class="event_details">
  <main class="mt-3 pt-4 main">
    <div class="container dark-grey-text">
      <div class="row wow fadeIn">
        <div class="col-md-12 mb-4 information">
            <div id="carouselExampleCaptions" class="carousel slide mb-5" data-ride="carousel" style="height: 500px;">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                  <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="{{ object.image1.url }}" class="d-block w-100" alt="image1" height="550px">
                  </div>
                  <div class="carousel-item">
                    <img src="{{ object.image2.url }}"class="d-block w-100" alt="image2" height="550px">
                  </div>
                  <div class="carousel-item">
                    <img src="{{ object.image3.url }}" class="d-block w-100" alt="image3" height="550px">
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="p-4 content">
                <div>
                    <h1 class="text-center"><u>{{ object.event.title }}</u></h1>
                </div>
                <div class="lead">
                    <h5 class="text-center">{{ object.event.cause }}</h5>
                    <h5 class="text-center">{{ object.event.location }} , {{ object.event.event_timings }}</h5>
                    <h5 class="text-center">Event description:</h5> 
                    <h5 class="text-center">{{ object.details }}</h5>
                    <h5 class="text-center">Impact On Society:</h5>
                    <h5 class="text-center">{{ object.impact_on_society }}</h5> 
                    <h5 class="text-center">Awards: </h5>
                    <h5 class="text-center">{{ object.awards }}</h5>
                </div>
            </div>
        </div>
      </div>
    </div>
  </main>
</div>
{% endblock %}

main/templates/main/achievement_form.html
{% extends "main/layout.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="form">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Add Achievement</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/completed_list.html
{% extends "main/layout.html" %}
{% block content %}
<div class="list">
    <h1 class="text-center">Completed Events List</h1>
    <div class="row">
        <div class="col-sm-11 m-auto">
            {% if completed_events %}
            <div class="table-responsive">
                <table class="table table-dark">
                    <thead>
                    <tr>
                        <th scope="col">Title</th>
                        <th scope="col">Location</th>
                        <td scope="col">Started On</td>
                        <th scope="col">Funds Used</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for completed_event in completed_events %}
                    <tr>
                        <td><a href="#" class="text-white"><u>{{  completed_event.event.title }}</u></a></td>
                        <td>{{ completed_event.event.location }}</td>
                        <td>{{ completed_event.event.event_timings }}</td>
                        <td>{{ completed_event.funds_used }}</td>
                        <td><a class="btn btn-success" href="{% url 'main:achievement-update' completed_event.id %}">Update</a></td>
                        <td><a class="btn btn-danger" href="{% url 'main:achievement-delete' completed_event.id %}">Delete</a></td>
                    </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/donation_form.html
{% extends "main/layout.html" %}
{% block content %}
<div class="donation_form">
    <div class="form container mt-5 mb-3">
        <div class="row">
          <div class="col-sm-8 m-auto card bg-dark">
            <h2 class="text-center text-light">Donate:</h2>
            <form action="{% url 'main:donateFunds' %}" method="POST" class="mb-3 mt-3">
              {% csrf_token %}
              <div class="row">
                <div class="col-sm-12 mb-3">
                  <input type="text" name="pancard" class="form-control" placeholder="Enter Pancard Number">
                </div>
                <div class="col-sm-12 mb-3">
                  <input type="float" name="amount_donated" class="form-control" placeholder="Enter Amount To Be Donated">
                </div>
                <div class="col-sm-12 mb-3">
                    <input type="text" name="bank_name" class="form-control" placeholder="Enter Bank Name">
                </div>
                <div class="col-sm-12 mb-3">
                    <input type="text" name="bank_branch" class="form-control" placeholder="Enter Bank Branch">
                </div>
                <div class="col-sm-12 mb-3">
                    <label for="payment_method" class="text-light">Choose a Payment Method:</label>
                    <select name="payment_method" id="payment_method">
                        <option value="BankTransfer">BankTransfer</option>
                        <option value="PayTM">PayTM</option>
                        <option value="GooglePay">GooglePay</option>
                        <option value="CreditCard">CreditCard</option>
                        <option value="DebitCard">DebitCard</option>
                    </select>
                </div>
                <div class="col-sm-1 m-auto">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </div>
            </form>
          </div>
        </div>  
      </div>
</div>
{% endblock %}

main/templates/main/donations.html
{% extends "main/layout.html" %}
{% block content %}
<div class="list">
    <h1 class="text-center">Donations Received</h1>
    <div class="row">
        <div class="col-sm-11 m-auto">
            {% if donations %}
            <div class="table-responsive">
                <table class="table table-dark">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Donated By:</th>
                        <th scope="col">Amount Donated</th>
                        <th scope="col">Donated On</th>
                        <th scope="col">Bank Name</th>
                        <th scope="col">Branch Name</th>
                        <th scope="col">Payment Method</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for donation in donations %}
                    <tr>
                        <td>{{ donation.id }}</td>
                        <td>{{ donation.donated_by }}</td>
                        <td>{{ donation.amount_donated }}</td>
                        <td>{{ donation.donated_on }}</td>
                        <td>{{ donation.bank_name }}</td>
                        <td>{{ donation.bank_branch }}</td>
                        <td>{{ donation.payment_method }}</td>'
                    </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/event_confirm_delete.html
{% extends "main/layout.html" %}
{% block content %}
    <div class="content-section container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Event</legend>
                <h2>Are you sure you want to delete this event {{ event.title }}</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'main:home' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

main/templates/main/event_detail.html
{% extends "main/layout.html" %}
{% block content %}
<div class="event_details">
  <main class="mt-3 pt-4 main">
    <div class="container dark-grey-text">
      <div class="row wow fadeIn">
        <div class="col-md-12 mb-4 information">
            <div class="p-4 content">
                <div class="mt-0">
                    <h2 class="text-center"><u>{{ object.title }}</u></h2>
                </div>
                <div class="lead">
                    <h4 class="text-center">{{ object.cause }}</h4>
                    <h5 class="text-center">Location: {{ object.location }}</h5>
                    <h5 class="text-center">Timings : {{ object.event_timings }}</h5> 
                    <h5 class="text-center">{{ object.duration }}</h5>
                    <h5>{{ object.description }}</h5>
                    <hr>
                    {% if user.is_authenticated %}
                      <div class="modal_class text-center">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                          Volunteer
                        </button>
                        
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to volunteer for this event??</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                  <h6 class="text-muted">*You must be available during the whole time of the event and should have complete focus at your volunteering duties!!</h6>
                                  <h5>*Once confirmed,we shall call you shortly and provide you with all the details of the event and also the responsibility you will be appointed to!!!Hoping to see you!!!</h5>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-dismiss="modal"><a href="{% url 'main:event-detail' object.slug %}">Close</a></button>
                                <button type="button" class="btn btn-warning"><a href="{% url 'main:volunteering' object.slug %}">Confirm</a></button>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endif %}
                </div>
            </div>
        </div>
      </div>
    </div>
  </main>
</div>
{% endblock %}

main/templates/main/layout.html
{% load get_group %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>NGO</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><h3>NGO</h3></a>
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav ml-auto">
                    <li><a href="{% url 'main:home' %}" class="mr-2 text-light">Home</a></li>
                    {% if user.is_authenticated %}
                        {% if request.user|has_group:"ngo_admin" %} 
                            <li><a href="{% url 'main:events_list' %}" class="mr-2 text-light">Events</a></li>
                            <li><a href="{% url 'main:completed_list' %}" class="mr-2 text-light">Achievements</a></li>
                            <li><a href="{% url 'main:event-add' %}" class="mr-2 text-light">AddEvent</a></li>
                            <li><a href="{% url 'main:achievement-add' %}" class="mr-2 text-light">AddAchievement</a></li>
                            <li><a href="{% url 'main:donations_received' %}" class="mr-2 text-light">Donations</a></li>
                            <li>
                                <form class="logout-link" action="{% url 'main:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="mr-2">Logout</button>
                                </form>
                            </li> 
                        {% else %}
                            <li><a href="{% url 'main:donation_form' %}" class="mr-2 text-light">Donate</a></li>
                            <li><a href="{% url 'main:user_dashboard' %}" class="mr-2 text-light">User Dashboard</a></li>
                            <li>
                                <form class="logout-link" action="{% url 'main:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="mr-2">Logout</button>
                                </form>
                            </li>
                        {% endif %}
                    {% else %}
                        <li><a href="{% url 'main:login' %}" class="mr-2 text-light">Login</a></li>
                        <li><a href="{% url 'main:signup' %}" class="mr-2 text-light">SignUp</a></li>
                    {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/signup.html
{% extends "main/layout.html" %}
{% load crispy_forms_tags %} 
{% block content %}
<div class="container">
    <h1>Signup</h1>
    <div class="form-border">
        <form class="site-form" action="{% url 'main:signup' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Signup" class="btn">
        </form>
    </div>
</div>
{% endblock %}